services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz-connect-postgres
    environment:
      POSTGRES_DB: quiz_connect_db
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: quiz-connect-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: quiz-connect-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quiz_connect_db
      SPRING_DATASOURCE_USERNAME: saurabhjojare
      SPRING_DATASOURCE_PASSWORD: Saurabh@123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
