server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/quiz_connect_db
    username: saurabhjojare
    password: Saurabh@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  devtools:
    restart:
      enabled: true

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR