server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/quiz_connect_db
    username: saurabhjojare
    password: Saurabh@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true